path: require "path"
fs: require "fs"
sys: require "sys"
require.paths.push(path.join("..", "jasmine", "contrib", "node"))



task 'test', 'run jasmine specs', ->
    GLOBAL.Game: {}
    jasmine: require "jasmine-node"
    jasmine.includeAll("server/classes/*.js")
    jasmine.runDefaultNodeSpecs()
    
