application: blok
version: 1
runtime: python
api_version: 1

handlers:

- url: /templates
  static_dir: templates
  
- url: /static
  static_dir: static
  
- url: /block
  static_dir: block

- url: .*
  script: main.py


  